import { writeFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { enterStudent, openTeacherExport } from "./helpers";

test("complete pilot flow", async ({ page }) => {
  await enterStudent(page);
  await page.getByRole("button", { name: "이해했어요" }).click();
  await page.getByLabel("중심 생각").fill("일회용 플라스틱은 줄여야 한다");
  await page.getByLabel("근거 또는 예시 1").fill("분해가 오래 걸린다");
  await page.getByLabel("근거 또는 예시 2").fill("생태계에 피해를 준다");
  await page.getByLabel("출처 메모").fill("- 지문: 플라스틱 분해와 생태계 피해 문장");
  await page.getByLabel("설명 또는 연결 1").fill("환경 피해가 오랫동안 이어지기 때문이다.");
  await page.getByLabel("반대 의견").fill("편리함도 중요하다는 반론이 있다.");
  await page.getByRole("button", { name: "초안 쓰기 시작" }).click();
  await page.getByTestId("draft-editor").fill("일회용 플라스틱은 줄여야 한다. 근거는 분해가 오래 걸리고 생태계에 피해를 주기 때문이다.");
  await page.getByRole("button", { name: "고쳐쓰기 시작" }).click();
  await page.getByRole("button", { name: "해결 표시" }).first().click();
  await expect(page.getByRole("button", { name: "확인됨" })).toBeVisible();
  await page.getByRole("button", { name: "제출" }).click();
  await expect(page.getByText("제출 완료")).toBeVisible();
  await openTeacherExport(page);
  const raw = await page.getByTestId("export-json").textContent();
  const exported: unknown = JSON.parse(raw ?? "{}");
  expect(exported).toHaveProperty("sessions.0.finalSubmission.text");
  expect(exported).toHaveProperty("sessions.0.student.accountId", "student-minseo");
  expect(exported).toHaveProperty("students.0.displayName", "김민서");
  expect(JSON.stringify(exported)).toContain("submission_created");
  expect(JSON.stringify(exported)).toContain("stage_completed");
  expect(JSON.stringify(exported)).toContain("feedback_generated");
  expect(JSON.stringify(exported)).toContain("feedback_viewed");
  expect(JSON.stringify(exported)).toContain("suggestion_resolved");
  await writeFile(".omo/evidence/pilot-writing-coach-v0/task-11-export.json", raw ?? "{}", "utf8");
});
